DECLARE
    v_count     INT;
    v_name      VARCHAR2(20);

    TYPE NAMESARRAY IS VARRAY(14) OF VARCHAR2(20);
    v_table    NAMESARRAY;

BEGIN
    v_table := NAMESARRAY(
        'doctors',
        'patients',
        'appointments',
        'offices',
        'hospitals',
        'addresses',
        'cities',
        'countries',
        'regions',
        'reg_countries',
        'dependents',
        'specialization',
        'accounts'
    );

    FOR name IN 1..v_table.COUNT
    LOOP
        v_name := v_table(name);

        SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = UPPER(v_name);

        IF v_count = 1 THEN
            DBMS_OUTPUT.PUT_LINE('Dropping table ' || UPPER(v_name));
            EXECUTE IMMEDIATE 'DROP TABLE ' || v_name || ' CASCADE CONSTRAINTS';
        END IF;
    END LOOP;
END;

/

CREATE TABLE regions(
    region_id       NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT reg_pk PRIMARY KEY,
    name            VARCHAR2 (40) NOT NULL,
    shortname       VARCHAR2(10)
);

CREATE TABLE countries(
    country_id      NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT ctr_pk PRIMARY KEY,
    name            VARCHAR2 (40) NOT NULL,
    capital         NUMBER,
    population      NUMBER CONSTRAINT countries_pop_check CHECK (population > 0),
    language        VARCHAR2(50),
    currency        VARCHAR2(10),
    domain          VARCHAR2(5),
    code            VARCHAR2(5),
    phone_code      VARCHAR2(5)
);

CREATE TABLE reg_countries(
    rc_id           NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT rc_pk PRIMARY KEY,
    region_id       NUMBER NOT NULL CONSTRAINT rc_reg_fk REFERENCES regions (region_id),
    country_id      NUMBER NOT NULL CONSTRAINT rc_ctr_fk REFERENCES countries (country_id)
);

CREATE TABLE cities(
    city_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT ct_pk PRIMARY KEY,
    name            VARCHAR2(40) NOT NULL,
    population      NUMBER CONSTRAINT cities_pop_check CHECK (population > 0),
    country_id      NUMBER (4) NOT NULL CONSTRAINT ct_ctr_fk REFERENCES countries (country_id)
);

CREATE TABLE addresses(
    address_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT addr_pk PRIMARY KEY,
    street          VARCHAR2 (40) NOT NULL,
    postal_code     VARCHAR2 (40) NOT NULL,
    city_id         NUMBER (4) NOT NULL CONSTRAINT addr_ct_fk REFERENCES cities (city_id)
);

CREATE TABLE doctors(
    pesel           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT doc_pk PRIMARY KEY,
    name            VARCHAR2(40) NOT NULL,
    surname         VARCHAR2(40) NOT NULL,
    birth_date      DATE NOT NULL,
    spec_id         NUMBER,
    gender          CHAR(1) CONSTRAINT doc_gender_check CHECK (gender IN ('K', 'M', 'N')),
    hospital_id     NUMBER
);

CREATE TABLE hospitals(
    hospital_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT hos_pk PRIMARY KEY,
    address         NUMBER NOT NULL CONSTRAINT hos_add_fk REFERENCES addresses (address_id),
    name            VARCHAR2(40) NOT NULL,
    established     DATE NOT NULL,
    contact         NUMBER NOT NULL,
    administrator   NUMBER NOT NULL CONSTRAINT hos_doc_fk REFERENCES doctors (pesel)
);

CREATE TABLE offices(
    office_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT ofc_pk PRIMARY KEY,
    hospital_id     NUMBER NOT NULL CONSTRAINT ofc_hos_fk REFERENCES hospitals (hospital_id),
    room            NUMBER NOT NULL
);

CREATE TABLE patients(
    pesel           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT pat_pk PRIMARY KEY,
    name            VARCHAR2(40) NOT NULL,
    surname         VARCHAR2(40) NOT NULL,
    birth_date      DATE NOT NULL,
    description     VARCHAR2(140),
    gender          CHAR(1) CONSTRAINT pat_gender_check CHECK (gender IN ('K', 'M', 'N'))
);

CREATE TABLE accounts(
    account_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT acc_pk PRIMARY KEY,
    login           VARCHAR2(40) NOT NULL,
    password        VARCHAR2(40) NOT NULL,
    doctor_id       NUMBER NOT NULL CONSTRAINT acc_doc_fk REFERENCES doctors (pesel)
);

CREATE TABLE appointments(
    appointment_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT app_pk PRIMARY KEY,
    doctor          NUMBER NOT NULL CONSTRAINT app_doc_fk REFERENCES doctors (pesel),
    patient         NUMBER NOT NULL CONSTRAINT app_pat_fk REFERENCES patients (pesel),
    time            TIMESTAMP NOT NULL,
    office_id       NUMBER NOT NULL CONSTRAINT app_ofc_fk REFERENCES offices (office_id)
);

CREATE TABLE dependents(
    pesel           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT dependents_pk PRIMARY KEY,
    name            VARCHAR2(50) NOT NULL,
    surname         VARCHAR2(50) NOT NULL,
    birth_date      DATE NOT NULL,
    description     VARCHAR2(140),
    gender          CHAR (1) CONSTRAINT dep_gender_check CHECK (gender IN ('K', 'M', 'N')),
    parent_id       NUMBER CONSTRAINT dep_pat_fk REFERENCES patients (pesel)
);

DROP TABLE specializations;

CREATE TABLE specializations(
    spec_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY CONSTRAINT spec_pk PRIMARY KEY,
    name            VARCHAR2(40) NOT NULL,
    min_salary      NUMBER(7,2),
    max_salary      NUMBER(7,2),
    supervisor      NUMBER CONSTRAINT spec_doc_fk REFERENCES doctors (pesel)
);

ALTER TABLE doctors
ADD CONSTRAINT doc_spec_fk FOREIGN KEY (spec_id) REFERENCES specializations (spec_id);

ALTER TABLE doctors
ADD CONSTRAINT doc_hos_fk FOREIGN KEY (hospital_id) REFERENCES hospitals (hospital_id);

ALTER TABLE countries
ADD CONSTRAINT ctr_ct_fk FOREIGN KEY (capital) REFERENCES cities (city_id);
